package cn.itcraft.jdbcmon.wrap;

import cn.itcraft.jdbcmon.monitor.SqlMonitor;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public final class MonitoredStatement implements Statement {

    private final Statement delegate;
    private final SqlMonitor monitor;

    public MonitoredStatement(Statement delegate, SqlMonitor monitor) {
        this.delegate = delegate;
        this.monitor = monitor;
    }

    // ========== 监控方法 ==========

    @Override
    public boolean execute(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, autoGeneratedKeys);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, columnIndexes);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, columnNames);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public ResultSet executeQuery(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            ResultSet rs = delegate.executeQuery(sql);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return rs;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, autoGeneratedKeys);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, columnIndexes);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, columnNames);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int[] executeBatch() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int[] rows = delegate.executeBatch();
            monitor.recordBatch("BATCH", System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError("BATCH", System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public long[] executeLargeBatch() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long[] rows = delegate.executeLargeBatch();
            int[] intRows = new int[rows.length];
            for (int i = 0; i < rows.length; i++) {
                intRows[i] = (int) Math.min(rows[i], Integer.MAX_VALUE);
            }
            monitor.recordBatch("BATCH", System.nanoTime() - start, intRows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError("BATCH", System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public long executeLargeUpdate(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long rows = delegate.executeLargeUpdate(sql);
            monitor.recordUpdate(sql, System.nanoTime() - start, (int) Math.min(rows, Integer.MAX_VALUE));
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long rows = delegate.executeLargeUpdate(sql, autoGeneratedKeys);
            monitor.recordUpdate(sql, System.nanoTime() - start, (int) Math.min(rows, Integer.MAX_VALUE));
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long rows = delegate.executeLargeUpdate(sql, columnIndexes);
            monitor.recordUpdate(sql, System.nanoTime() - start, (int) Math.min(rows, Integer.MAX_VALUE));
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long rows = delegate.executeLargeUpdate(sql, columnNames);
            monitor.recordUpdate(sql, System.nanoTime() - start, (int) Math.min(rows, Integer.MAX_VALUE));
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    // ========== 非监控方法：直接委托 ==========

    @Override
    public void addBatch(String sql) throws java.sql.SQLException {
        delegate.addBatch(sql);
    }

    @Override
    public void clearBatch() throws java.sql.SQLException {
        delegate.clearBatch();
    }

    @Override
    public void close() throws java.sql.SQLException {
        delegate.close();
    }

    @Override
    public void cancel() throws java.sql.SQLException {
        delegate.cancel();
    }

    @Override
    public Connection getConnection() throws java.sql.SQLException {
        return delegate.getConnection();
    }

    @Override
    public ResultSet getGeneratedKeys() throws java.sql.SQLException {
        return delegate.getGeneratedKeys();
    }

    @Override
    public int getUpdateCount() throws java.sql.SQLException {
        return delegate.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws java.sql.SQLException {
        return delegate.getMoreResults();
    }

    @Override
    public boolean getMoreResults(int current) throws java.sql.SQLException {
        return delegate.getMoreResults(current);
    }

    @Override
    public ResultSet getResultSet() throws java.sql.SQLException {
        return delegate.getResultSet();
    }

    @Override
    public int getResultSetConcurrency() throws java.sql.SQLException {
        return delegate.getResultSetConcurrency();
    }

    @Override
    public int getResultSetHoldability() throws java.sql.SQLException {
        return delegate.getResultSetHoldability();
    }

    @Override
    public int getResultSetType() throws java.sql.SQLException {
        return delegate.getResultSetType();
    }

    @Override
    public int getFetchDirection() throws java.sql.SQLException {
        return delegate.getFetchDirection();
    }

    @Override
    public void setFetchDirection(int direction) throws java.sql.SQLException {
        delegate.setFetchDirection(direction);
    }

    @Override
    public int getFetchSize() throws java.sql.SQLException {
        return delegate.getFetchSize();
    }

    @Override
    public void setFetchSize(int rows) throws java.sql.SQLException {
        delegate.setFetchSize(rows);
    }

    @Override
    public int getMaxFieldSize() throws java.sql.SQLException {
        return delegate.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws java.sql.SQLException {
        delegate.setMaxFieldSize(max);
    }

    @Override
    public int getMaxRows() throws java.sql.SQLException {
        return delegate.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws java.sql.SQLException {
        delegate.setMaxRows(max);
    }

    @Override
    public long getLargeMaxRows() throws java.sql.SQLException {
        return delegate.getLargeMaxRows();
    }

    @Override
    public void setLargeMaxRows(long max) throws java.sql.SQLException {
        delegate.setLargeMaxRows(max);
    }

    @Override
    public int getQueryTimeout() throws java.sql.SQLException {
        return delegate.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws java.sql.SQLException {
        delegate.setQueryTimeout(seconds);
    }

    @Override
    public boolean isClosed() throws java.sql.SQLException {
        return delegate.isClosed();
    }

    @Override
    public boolean isPoolable() throws java.sql.SQLException {
        return delegate.isPoolable();
    }

    @Override
    public void setPoolable(boolean poolable) throws java.sql.SQLException {
        delegate.setPoolable(poolable);
    }

    @Override
    public void setCursorName(String name) throws java.sql.SQLException {
        delegate.setCursorName(name);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws java.sql.SQLException {
        return delegate.isWrapperFor(iface);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws java.sql.SQLException {
        return delegate.unwrap(iface);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws java.sql.SQLException {
        delegate.setEscapeProcessing(enable);
    }

    @Override
    public void closeOnCompletion() throws java.sql.SQLException {
        delegate.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws java.sql.SQLException {
        return delegate.isCloseOnCompletion();
    }

    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException {
        return delegate.getWarnings();
    }

    @Override
    public void clearWarnings() throws java.sql.SQLException {
        delegate.clearWarnings();
    }

    // ========== Object 方法 ==========

    @Override
    public int hashCode() {
        return delegate.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return delegate.equals(obj);
    }

    @Override
    public String toString() {
        return "MonitoredStatement[" + delegate + "]";
    }
}