package cn.itcraft.jdbcmon.wrap;

import cn.itcraft.jdbcmon.config.WrappedConfig;
import cn.itcraft.jdbcmon.monitor.SqlMonitor;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public final class MonitoredConnection implements Connection {

    private final Connection delegate;
    private final SqlMonitor monitor;
    private final WrappedConfig config;

    public MonitoredConnection(Connection delegate, SqlMonitor monitor, WrappedConfig config) {
        this.delegate = delegate;
        this.monitor = monitor;
        this.config = config;
    }

    // ========== 监控方法：创建 Statement ==========

    @Override
    public Statement createStatement() throws java.sql.SQLException {
        Statement stmt = delegate.createStatement();
        return new MonitoredStatement(stmt, monitor);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws java.sql.SQLException {
        Statement stmt = delegate.createStatement(resultSetType, resultSetConcurrency);
        return new MonitoredStatement(stmt, monitor);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws java.sql.SQLException {
        Statement stmt = delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
        return new MonitoredStatement(stmt, monitor);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql, autoGeneratedKeys);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql, columnIndexes);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql, columnNames);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws java.sql.SQLException {
        PreparedStatement stmt = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        return new MonitoredPreparedStatement(stmt, monitor, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws java.sql.SQLException {
        CallableStatement stmt = delegate.prepareCall(sql);
        return new MonitoredCallableStatement(stmt, monitor, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws java.sql.SQLException {
        CallableStatement stmt = delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
        return new MonitoredCallableStatement(stmt, monitor, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws java.sql.SQLException {
        CallableStatement stmt = delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        return new MonitoredCallableStatement(stmt, monitor, sql);
    }

    // ========== 监控方法：事务 ==========

    @Override
    public void commit() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            delegate.commit();
            monitor.recordTransaction("COMMIT", System.nanoTime() - start);
        } catch (java.sql.SQLException e) {
            monitor.recordError("COMMIT", System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public void rollback() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            delegate.rollback();
            monitor.recordTransaction("ROLLBACK", System.nanoTime() - start);
        } catch (java.sql.SQLException e) {
            monitor.recordError("ROLLBACK", System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public void rollback(Savepoint savepoint) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            delegate.rollback(savepoint);
            monitor.recordTransaction("ROLLBACK_SAVEPOINT", System.nanoTime() - start);
        } catch (java.sql.SQLException e) {
            monitor.recordError("ROLLBACK_SAVEPOINT", System.nanoTime() - start, e);
            throw e;
        }
    }

    // ========== 非监控方法：直接委托 ==========

    @Override
    public void close() throws java.sql.SQLException {
        delegate.close();
    }

    @Override
    public boolean isClosed() throws java.sql.SQLException {
        return delegate.isClosed();
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws java.sql.SQLException {
        delegate.setAutoCommit(autoCommit);
    }

    @Override
    public boolean getAutoCommit() throws java.sql.SQLException {
        return delegate.getAutoCommit();
    }

    @Override
    public DatabaseMetaData getMetaData() throws java.sql.SQLException {
        return delegate.getMetaData();
    }

    @Override
    public void setReadOnly(boolean readOnly) throws java.sql.SQLException {
        delegate.setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws java.sql.SQLException {
        return delegate.isReadOnly();
    }

    @Override
    public void setCatalog(String catalog) throws java.sql.SQLException {
        delegate.setCatalog(catalog);
    }

    @Override
    public String getCatalog() throws java.sql.SQLException {
        return delegate.getCatalog();
    }

    @Override
    public void setTransactionIsolation(int level) throws java.sql.SQLException {
        delegate.setTransactionIsolation(level);
    }

    @Override
    public int getTransactionIsolation() throws java.sql.SQLException {
        return delegate.getTransactionIsolation();
    }

    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException {
        return delegate.getWarnings();
    }

    @Override
    public void clearWarnings() throws java.sql.SQLException {
        delegate.clearWarnings();
    }

    @Override
    public String nativeSQL(String sql) throws java.sql.SQLException {
        return delegate.nativeSQL(sql);
    }

    @Override
    public Savepoint setSavepoint() throws java.sql.SQLException {
        return delegate.setSavepoint();
    }

    @Override
    public Savepoint setSavepoint(String name) throws java.sql.SQLException {
        return delegate.setSavepoint(name);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws java.sql.SQLException {
        delegate.releaseSavepoint(savepoint);
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws java.sql.SQLException {
        return delegate.getTypeMap();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws java.sql.SQLException {
        delegate.setTypeMap(map);
    }

    @Override
    public void setHoldability(int holdability) throws java.sql.SQLException {
        delegate.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws java.sql.SQLException {
        return delegate.getHoldability();
    }

    @Override
    public boolean isValid(int timeout) throws java.sql.SQLException {
        return delegate.isValid(timeout);
    }

    @Override
    public String getSchema() throws java.sql.SQLException {
        return delegate.getSchema();
    }

    @Override
    public void setSchema(String schema) throws java.sql.SQLException {
        delegate.setSchema(schema);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws java.sql.SQLException {
        return delegate.isWrapperFor(iface);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws java.sql.SQLException {
        return delegate.unwrap(iface);
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws java.sql.SQLException {
        return delegate.createArrayOf(typeName, elements);
    }

    @Override
    public Blob createBlob() throws java.sql.SQLException {
        return delegate.createBlob();
    }

    @Override
    public Clob createClob() throws java.sql.SQLException {
        return delegate.createClob();
    }

    @Override
    public NClob createNClob() throws java.sql.SQLException {
        return delegate.createNClob();
    }

    @Override
    public SQLXML createSQLXML() throws java.sql.SQLException {
        return delegate.createSQLXML();
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws java.sql.SQLException {
        return delegate.createStruct(typeName, attributes);
    }

    @Override
    public Properties getClientInfo() throws java.sql.SQLException {
        return delegate.getClientInfo();
    }

    @Override
    public String getClientInfo(String name) throws java.sql.SQLException {
        return delegate.getClientInfo(name);
    }

    @Override
    public void setClientInfo(Properties properties) {
        try {
            delegate.setClientInfo(properties);
        } catch (java.sql.SQLClientInfoException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void setClientInfo(String name, String value) {
        try {
            delegate.setClientInfo(name, value);
        } catch (java.sql.SQLClientInfoException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void abort(Executor executor) throws java.sql.SQLException {
        delegate.abort(executor);
    }

    @Override
    public int getNetworkTimeout() throws java.sql.SQLException {
        return delegate.getNetworkTimeout();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws java.sql.SQLException {
        delegate.setNetworkTimeout(executor, milliseconds);
    }

    // ========== Object 方法 ==========

    @Override
    public int hashCode() {
        return delegate.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return delegate.equals(obj);
    }

    @Override
    public String toString() {
        return "MonitoredConnection[" + delegate + "]";
    }
}