package cn.itcraft.jdbcmon.proxy.wrapper;

import cn.itcraft.jdbcmon.monitor.SqlMonitor;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLType;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

public final class MonitoredCallableStatement implements CallableStatement {

    private final CallableStatement delegate;
    private final SqlMonitor monitor;
    private final String sql;

    public MonitoredCallableStatement(CallableStatement delegate, SqlMonitor monitor, String sql) {
        this.delegate = delegate;
        this.monitor = monitor;
        this.sql = sql;
    }

    // ========== 监控方法 ==========

    @Override
    public boolean execute() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute();
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public ResultSet executeQuery() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            ResultSet rs = delegate.executeQuery();
            monitor.recordQuery(sql, System.nanoTime() - start);
            return rs;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate();
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int[] executeBatch() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int[] rows = delegate.executeBatch();
            monitor.recordBatch(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    // ========== Statement 接口的 execute/update 方法（带 SQL 参数）==========

    @Override
    public boolean execute(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, autoGeneratedKeys);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, columnIndexes);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            boolean result = delegate.execute(sql, columnNames);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return result;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public ResultSet executeQuery(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            ResultSet rs = delegate.executeQuery(sql);
            monitor.recordQuery(sql, System.nanoTime() - start);
            return rs;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, autoGeneratedKeys);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, columnIndexes);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            int rows = delegate.executeUpdate(sql, columnNames);
            monitor.recordUpdate(sql, System.nanoTime() - start, rows);
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    // ========== 非监控方法：直接委托（仅列出关键方法）==========

    @Override
    public void addBatch() throws java.sql.SQLException { delegate.addBatch(); }
    @Override
    public void addBatch(String sql) throws java.sql.SQLException { delegate.addBatch(sql); }
    @Override
    public void clearBatch() throws java.sql.SQLException { delegate.clearBatch(); }
    @Override
    public void clearParameters() throws java.sql.SQLException { delegate.clearParameters(); }
    @Override
    public void close() throws java.sql.SQLException { delegate.close(); }
    @Override
    public void cancel() throws java.sql.SQLException { delegate.cancel(); }
    @Override
    public Connection getConnection() throws java.sql.SQLException { return delegate.getConnection(); }
    @Override
    public ResultSet getGeneratedKeys() throws java.sql.SQLException { return delegate.getGeneratedKeys(); }
    @Override
    public ResultSetMetaData getMetaData() throws java.sql.SQLException { return delegate.getMetaData(); }
    @Override
    public ParameterMetaData getParameterMetaData() throws java.sql.SQLException { return delegate.getParameterMetaData(); }
    @Override
    public int getUpdateCount() throws java.sql.SQLException { return delegate.getUpdateCount(); }
    @Override
    public boolean getMoreResults() throws java.sql.SQLException { return delegate.getMoreResults(); }
    @Override
    public boolean getMoreResults(int current) throws java.sql.SQLException { return delegate.getMoreResults(current); }
    @Override
    public ResultSet getResultSet() throws java.sql.SQLException { return delegate.getResultSet(); }
    @Override
    public int getResultSetConcurrency() throws java.sql.SQLException { return delegate.getResultSetConcurrency(); }
    @Override
    public int getResultSetHoldability() throws java.sql.SQLException { return delegate.getResultSetHoldability(); }
    @Override
    public int getResultSetType() throws java.sql.SQLException { return delegate.getResultSetType(); }
    @Override
    public int getFetchDirection() throws java.sql.SQLException { return delegate.getFetchDirection(); }
    @Override
    public void setFetchDirection(int direction) throws java.sql.SQLException { delegate.setFetchDirection(direction); }
    @Override
    public int getFetchSize() throws java.sql.SQLException { return delegate.getFetchSize(); }
    @Override
    public void setFetchSize(int rows) throws java.sql.SQLException { delegate.setFetchSize(rows); }
    @Override
    public int getMaxFieldSize() throws java.sql.SQLException { return delegate.getMaxFieldSize(); }
    @Override
    public void setMaxFieldSize(int max) throws java.sql.SQLException { delegate.setMaxFieldSize(max); }
    @Override
    public int getMaxRows() throws java.sql.SQLException { return delegate.getMaxRows(); }
    @Override
    public void setMaxRows(int max) throws java.sql.SQLException { delegate.setMaxRows(max); }
    @Override
    public long getLargeMaxRows() throws java.sql.SQLException { return delegate.getLargeMaxRows(); }
    @Override
    public void setLargeMaxRows(long max) throws java.sql.SQLException { delegate.setLargeMaxRows(max); }
    @Override
    public int getQueryTimeout() throws java.sql.SQLException { return delegate.getQueryTimeout(); }
    @Override
    public void setQueryTimeout(int seconds) throws java.sql.SQLException { delegate.setQueryTimeout(seconds); }
    @Override
    public boolean isClosed() throws java.sql.SQLException { return delegate.isClosed(); }
    @Override
    public boolean isPoolable() throws java.sql.SQLException { return delegate.isPoolable(); }
    @Override
    public void setPoolable(boolean poolable) throws java.sql.SQLException { delegate.setPoolable(poolable); }
    @Override
    public void setCursorName(String name) throws java.sql.SQLException { delegate.setCursorName(name); }
    @Override
    public boolean isWrapperFor(Class<?> iface) throws java.sql.SQLException { return delegate.isWrapperFor(iface); }
    @Override
    public <T> T unwrap(Class<T> iface) throws java.sql.SQLException { return delegate.unwrap(iface); }
    @Override
    public void setEscapeProcessing(boolean enable) throws java.sql.SQLException { delegate.setEscapeProcessing(enable); }
    @Override
    public void closeOnCompletion() throws java.sql.SQLException { delegate.closeOnCompletion(); }
    @Override
    public boolean isCloseOnCompletion() throws java.sql.SQLException { return delegate.isCloseOnCompletion(); }
    @Override
    public java.sql.SQLWarning getWarnings() throws java.sql.SQLException { return delegate.getWarnings(); }
    @Override
    public void clearWarnings() throws java.sql.SQLException { delegate.clearWarnings(); }

    // ========== PreparedStatement 参数设置方法 ==========

    @Override
    public void setNull(int parameterIndex, int sqlType) throws java.sql.SQLException { delegate.setNull(parameterIndex, sqlType); }
    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws java.sql.SQLException { delegate.setNull(parameterIndex, sqlType, typeName); }
    @Override
    public void setBoolean(int parameterIndex, boolean x) throws java.sql.SQLException { delegate.setBoolean(parameterIndex, x); }
    @Override
    public void setByte(int parameterIndex, byte x) throws java.sql.SQLException { delegate.setByte(parameterIndex, x); }
    @Override
    public void setShort(int parameterIndex, short x) throws java.sql.SQLException { delegate.setShort(parameterIndex, x); }
    @Override
    public void setInt(int parameterIndex, int x) throws java.sql.SQLException { delegate.setInt(parameterIndex, x); }
    @Override
    public void setLong(int parameterIndex, long x) throws java.sql.SQLException { delegate.setLong(parameterIndex, x); }
    @Override
    public void setFloat(int parameterIndex, float x) throws java.sql.SQLException { delegate.setFloat(parameterIndex, x); }
    @Override
    public void setDouble(int parameterIndex, double x) throws java.sql.SQLException { delegate.setDouble(parameterIndex, x); }
    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws java.sql.SQLException { delegate.setBigDecimal(parameterIndex, x); }
    @Override
    public void setString(int parameterIndex, String x) throws java.sql.SQLException { delegate.setString(parameterIndex, x); }
    @Override
    public void setBytes(int parameterIndex, byte[] x) throws java.sql.SQLException { delegate.setBytes(parameterIndex, x); }
    @Override
    public void setDate(int parameterIndex, Date x) throws java.sql.SQLException { delegate.setDate(parameterIndex, x); }
    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws java.sql.SQLException { delegate.setDate(parameterIndex, x, cal); }
    @Override
    public void setTime(int parameterIndex, Time x) throws java.sql.SQLException { delegate.setTime(parameterIndex, x); }
    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws java.sql.SQLException { delegate.setTime(parameterIndex, x, cal); }
    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws java.sql.SQLException { delegate.setTimestamp(parameterIndex, x); }
    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws java.sql.SQLException { delegate.setTimestamp(parameterIndex, x, cal); }
    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws java.sql.SQLException { delegate.setAsciiStream(parameterIndex, x, length); }
    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws java.sql.SQLException { delegate.setAsciiStream(parameterIndex, x, length); }
    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws java.sql.SQLException { delegate.setAsciiStream(parameterIndex, x); }
    @Override
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws java.sql.SQLException { delegate.setUnicodeStream(parameterIndex, x, length); }
    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws java.sql.SQLException { delegate.setBinaryStream(parameterIndex, x, length); }
    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws java.sql.SQLException { delegate.setBinaryStream(parameterIndex, x, length); }
    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws java.sql.SQLException { delegate.setBinaryStream(parameterIndex, x); }
    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws java.sql.SQLException { delegate.setCharacterStream(parameterIndex, reader, length); }
    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws java.sql.SQLException { delegate.setCharacterStream(parameterIndex, reader, length); }
    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws java.sql.SQLException { delegate.setCharacterStream(parameterIndex, reader); }
    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws java.sql.SQLException { delegate.setObject(parameterIndex, x, targetSqlType); }
    @Override
    public void setObject(int parameterIndex, Object x) throws java.sql.SQLException { delegate.setObject(parameterIndex, x); }
    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws java.sql.SQLException { delegate.setObject(parameterIndex, x, targetSqlType, scaleOrLength); }
    @Override
    public void setObject(int parameterIndex, Object x, SQLType targetSqlType, int scaleOrLength) throws java.sql.SQLException { delegate.setObject(parameterIndex, x, targetSqlType, scaleOrLength); }
    @Override
    public void setObject(int parameterIndex, Object x, SQLType targetSqlType) throws java.sql.SQLException { delegate.setObject(parameterIndex, x, targetSqlType); }
    @Override
    public void setRef(int parameterIndex, Ref x) throws java.sql.SQLException { delegate.setRef(parameterIndex, x); }
    @Override
    public void setBlob(int parameterIndex, Blob x) throws java.sql.SQLException { delegate.setBlob(parameterIndex, x); }
    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws java.sql.SQLException { delegate.setBlob(parameterIndex, inputStream, length); }
    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws java.sql.SQLException { delegate.setBlob(parameterIndex, inputStream); }
    @Override
    public void setClob(int parameterIndex, Clob x) throws java.sql.SQLException { delegate.setClob(parameterIndex, x); }
    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws java.sql.SQLException { delegate.setClob(parameterIndex, reader, length); }
    @Override
    public void setClob(int parameterIndex, Reader reader) throws java.sql.SQLException { delegate.setClob(parameterIndex, reader); }
    @Override
    public void setArray(int parameterIndex, Array x) throws java.sql.SQLException { delegate.setArray(parameterIndex, x); }
    @Override
    public void setURL(int parameterIndex, URL x) throws java.sql.SQLException { delegate.setURL(parameterIndex, x); }
    @Override
    public void setRowId(int parameterIndex, RowId x) throws java.sql.SQLException { delegate.setRowId(parameterIndex, x); }
    @Override
    public void setRowId(String parameterName, RowId x) throws java.sql.SQLException { delegate.setRowId(parameterName, x); }
    @Override
    public void setNString(int parameterIndex, String value) throws java.sql.SQLException { delegate.setNString(parameterIndex, value); }
    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws java.sql.SQLException { delegate.setNCharacterStream(parameterIndex, value, length); }
    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws java.sql.SQLException { delegate.setNCharacterStream(parameterIndex, value); }
    @Override
    public void setNClob(int parameterIndex, NClob value) throws java.sql.SQLException { delegate.setNClob(parameterIndex, value); }
    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws java.sql.SQLException { delegate.setNClob(parameterIndex, reader, length); }
    @Override
    public void setNClob(int parameterIndex, Reader reader) throws java.sql.SQLException { delegate.setNClob(parameterIndex, reader); }
    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws java.sql.SQLException { delegate.setSQLXML(parameterIndex, xmlObject); }

    // ========== CallableStatement 特有方法 ==========

    @Override
    public void registerOutParameter(int parameterIndex, int sqlType) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType); }
    @Override
    public void registerOutParameter(int parameterIndex, int sqlType, int scale) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType, scale); }
    @Override
    public void registerOutParameter(int parameterIndex, int sqlType, String typeName) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType, typeName); }
    @Override
    public void registerOutParameter(String parameterName, int sqlType) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType); }
    @Override
    public void registerOutParameter(String parameterName, int sqlType, int scale) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType, scale); }
    @Override
    public void registerOutParameter(String parameterName, int sqlType, String typeName) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType, typeName); }
    @Override
    public boolean wasNull() throws java.sql.SQLException { return delegate.wasNull(); }
    @Override
    public String getString(int parameterIndex) throws java.sql.SQLException { return delegate.getString(parameterIndex); }
    @Override
    public boolean getBoolean(int parameterIndex) throws java.sql.SQLException { return delegate.getBoolean(parameterIndex); }
    @Override
    public byte getByte(int parameterIndex) throws java.sql.SQLException { return delegate.getByte(parameterIndex); }
    @Override
    public short getShort(int parameterIndex) throws java.sql.SQLException { return delegate.getShort(parameterIndex); }
    @Override
    public int getInt(int parameterIndex) throws java.sql.SQLException { return delegate.getInt(parameterIndex); }
    @Override
    public long getLong(int parameterIndex) throws java.sql.SQLException { return delegate.getLong(parameterIndex); }
    @Override
    public float getFloat(int parameterIndex) throws java.sql.SQLException { return delegate.getFloat(parameterIndex); }
    @Override
    public double getDouble(int parameterIndex) throws java.sql.SQLException { return delegate.getDouble(parameterIndex); }
    @Override
    public byte[] getBytes(int parameterIndex) throws java.sql.SQLException { return delegate.getBytes(parameterIndex); }
    @Override
    public Date getDate(int parameterIndex) throws java.sql.SQLException { return delegate.getDate(parameterIndex); }
    @Override
    public Time getTime(int parameterIndex) throws java.sql.SQLException { return delegate.getTime(parameterIndex); }
    @Override
    public Timestamp getTimestamp(int parameterIndex) throws java.sql.SQLException { return delegate.getTimestamp(parameterIndex); }
    @Override
    public Object getObject(int parameterIndex) throws java.sql.SQLException { return delegate.getObject(parameterIndex); }
    @Override
    public BigDecimal getBigDecimal(int parameterIndex, int scale) throws java.sql.SQLException { return delegate.getBigDecimal(parameterIndex, scale); }
    @Override
    public BigDecimal getBigDecimal(int parameterIndex) throws java.sql.SQLException { return delegate.getBigDecimal(parameterIndex); }
    @Override
    public Object getObject(int parameterIndex, Map<String, Class<?>> map) throws java.sql.SQLException { return delegate.getObject(parameterIndex, map); }
    @Override
    public Ref getRef(int parameterIndex) throws java.sql.SQLException { return delegate.getRef(parameterIndex); }
    @Override
    public Blob getBlob(int parameterIndex) throws java.sql.SQLException { return delegate.getBlob(parameterIndex); }
    @Override
    public Clob getClob(int parameterIndex) throws java.sql.SQLException { return delegate.getClob(parameterIndex); }
    @Override
    public Array getArray(int parameterIndex) throws java.sql.SQLException { return delegate.getArray(parameterIndex); }
    @Override
    public Date getDate(int parameterIndex, Calendar cal) throws java.sql.SQLException { return delegate.getDate(parameterIndex, cal); }
    @Override
    public Time getTime(int parameterIndex, Calendar cal) throws java.sql.SQLException { return delegate.getTime(parameterIndex, cal); }
    @Override
    public Timestamp getTimestamp(int parameterIndex, Calendar cal) throws java.sql.SQLException { return delegate.getTimestamp(parameterIndex, cal); }
    @Override
    public URL getURL(int parameterIndex) throws java.sql.SQLException { return delegate.getURL(parameterIndex); }
    @Override
    public String getString(String parameterName) throws java.sql.SQLException { return delegate.getString(parameterName); }
    @Override
    public boolean getBoolean(String parameterName) throws java.sql.SQLException { return delegate.getBoolean(parameterName); }
    @Override
    public byte getByte(String parameterName) throws java.sql.SQLException { return delegate.getByte(parameterName); }
    @Override
    public short getShort(String parameterName) throws java.sql.SQLException { return delegate.getShort(parameterName); }
    @Override
    public int getInt(String parameterName) throws java.sql.SQLException { return delegate.getInt(parameterName); }
    @Override
    public long getLong(String parameterName) throws java.sql.SQLException { return delegate.getLong(parameterName); }
    @Override
    public float getFloat(String parameterName) throws java.sql.SQLException { return delegate.getFloat(parameterName); }
    @Override
    public double getDouble(String parameterName) throws java.sql.SQLException { return delegate.getDouble(parameterName); }
    @Override
    public byte[] getBytes(String parameterName) throws java.sql.SQLException { return delegate.getBytes(parameterName); }
    @Override
    public Date getDate(String parameterName) throws java.sql.SQLException { return delegate.getDate(parameterName); }
    @Override
    public Time getTime(String parameterName) throws java.sql.SQLException { return delegate.getTime(parameterName); }
    @Override
    public Timestamp getTimestamp(String parameterName) throws java.sql.SQLException { return delegate.getTimestamp(parameterName); }
    @Override
    public Object getObject(String parameterName) throws java.sql.SQLException { return delegate.getObject(parameterName); }
    @Override
    public BigDecimal getBigDecimal(String parameterName) throws java.sql.SQLException { return delegate.getBigDecimal(parameterName); }
    @Override
    public Object getObject(String parameterName, Map<String, Class<?>> map) throws java.sql.SQLException { return delegate.getObject(parameterName, map); }
    @Override
    public Ref getRef(String parameterName) throws java.sql.SQLException { return delegate.getRef(parameterName); }
    @Override
    public Blob getBlob(String parameterName) throws java.sql.SQLException { return delegate.getBlob(parameterName); }
    @Override
    public Clob getClob(String parameterName) throws java.sql.SQLException { return delegate.getClob(parameterName); }
    @Override
    public Array getArray(String parameterName) throws java.sql.SQLException { return delegate.getArray(parameterName); }
    @Override
    public Date getDate(String parameterName, Calendar cal) throws java.sql.SQLException { return delegate.getDate(parameterName, cal); }
    @Override
    public Time getTime(String parameterName, Calendar cal) throws java.sql.SQLException { return delegate.getTime(parameterName, cal); }
    @Override
    public Timestamp getTimestamp(String parameterName, Calendar cal) throws java.sql.SQLException { return delegate.getTimestamp(parameterName, cal); }
    @Override
    public URL getURL(String parameterName) throws java.sql.SQLException { return delegate.getURL(parameterName); }
    @Override
    public RowId getRowId(int parameterIndex) throws java.sql.SQLException { return delegate.getRowId(parameterIndex); }
    @Override
    public RowId getRowId(String parameterName) throws java.sql.SQLException { return delegate.getRowId(parameterName); }
    @Override
    public void setURL(String parameterName, URL val) throws java.sql.SQLException { delegate.setURL(parameterName, val); }
    @Override
    public void setNull(String parameterName, int sqlType) throws java.sql.SQLException { delegate.setNull(parameterName, sqlType); }
    @Override
    public void setNull(String parameterName, int sqlType, String typeName) throws java.sql.SQLException { delegate.setNull(parameterName, sqlType, typeName); }
    @Override
    public void setBoolean(String parameterName, boolean x) throws java.sql.SQLException { delegate.setBoolean(parameterName, x); }
    @Override
    public void setByte(String parameterName, byte x) throws java.sql.SQLException { delegate.setByte(parameterName, x); }
    @Override
    public void setShort(String parameterName, short x) throws java.sql.SQLException { delegate.setShort(parameterName, x); }
    @Override
    public void setInt(String parameterName, int x) throws java.sql.SQLException { delegate.setInt(parameterName, x); }
    @Override
    public void setLong(String parameterName, long x) throws java.sql.SQLException { delegate.setLong(parameterName, x); }
    @Override
    public void setFloat(String parameterName, float x) throws java.sql.SQLException { delegate.setFloat(parameterName, x); }
    @Override
    public void setDouble(String parameterName, double x) throws java.sql.SQLException { delegate.setDouble(parameterName, x); }
    @Override
    public void setBigDecimal(String parameterName, BigDecimal x) throws java.sql.SQLException { delegate.setBigDecimal(parameterName, x); }
    @Override
    public void setString(String parameterName, String x) throws java.sql.SQLException { delegate.setString(parameterName, x); }
    @Override
    public void setBytes(String parameterName, byte[] x) throws java.sql.SQLException { delegate.setBytes(parameterName, x); }
    @Override
    public void setDate(String parameterName, Date x) throws java.sql.SQLException { delegate.setDate(parameterName, x); }
    @Override
    public void setDate(String parameterName, Date x, Calendar cal) throws java.sql.SQLException { delegate.setDate(parameterName, x, cal); }
    @Override
    public void setTime(String parameterName, Time x) throws java.sql.SQLException { delegate.setTime(parameterName, x); }
    @Override
    public void setTime(String parameterName, Time x, Calendar cal) throws java.sql.SQLException { delegate.setTime(parameterName, x, cal); }
    @Override
    public void setTimestamp(String parameterName, Timestamp x) throws java.sql.SQLException { delegate.setTimestamp(parameterName, x); }
    @Override
    public void setTimestamp(String parameterName, Timestamp x, Calendar cal) throws java.sql.SQLException { delegate.setTimestamp(parameterName, x, cal); }
    @Override
    public void setAsciiStream(String parameterName, InputStream x, int length) throws java.sql.SQLException { delegate.setAsciiStream(parameterName, x, length); }
    @Override
    public void setAsciiStream(String parameterName, InputStream x, long length) throws java.sql.SQLException { delegate.setAsciiStream(parameterName, x, length); }
    @Override
    public void setAsciiStream(String parameterName, InputStream x) throws java.sql.SQLException { delegate.setAsciiStream(parameterName, x); }
    @Override
    public void setBinaryStream(String parameterName, InputStream x, int length) throws java.sql.SQLException { delegate.setBinaryStream(parameterName, x, length); }
    @Override
    public void setBinaryStream(String parameterName, InputStream x, long length) throws java.sql.SQLException { delegate.setBinaryStream(parameterName, x, length); }
    @Override
    public void setBinaryStream(String parameterName, InputStream x) throws java.sql.SQLException { delegate.setBinaryStream(parameterName, x); }
    @Override
    public void setObject(String parameterName, Object x, int targetSqlType, int scale) throws java.sql.SQLException { delegate.setObject(parameterName, x, targetSqlType, scale); }
    @Override
    public void setObject(String parameterName, Object x, int targetSqlType) throws java.sql.SQLException { delegate.setObject(parameterName, x, targetSqlType); }
    @Override
    public void setObject(String parameterName, Object x) throws java.sql.SQLException { delegate.setObject(parameterName, x); }
    @Override
    public void setCharacterStream(String parameterName, Reader reader, int length) throws java.sql.SQLException { delegate.setCharacterStream(parameterName, reader, length); }
    @Override
    public void setCharacterStream(String parameterName, Reader reader, long length) throws java.sql.SQLException { delegate.setCharacterStream(parameterName, reader, length); }
    @Override
    public void setCharacterStream(String parameterName, Reader reader) throws java.sql.SQLException { delegate.setCharacterStream(parameterName, reader); }
    @Override
    public <T> T getObject(int parameterIndex, Class<T> type) throws java.sql.SQLException { return delegate.getObject(parameterIndex, type); }
    @Override
    public <T> T getObject(String parameterName, Class<T> type) throws java.sql.SQLException { return delegate.getObject(parameterName, type); }
    @Override
    public void setBlob(String parameterName, Blob x) throws java.sql.SQLException { delegate.setBlob(parameterName, x); }
    @Override
    public void setBlob(String parameterName, InputStream inputStream, long length) throws java.sql.SQLException { delegate.setBlob(parameterName, inputStream, length); }
    @Override
    public void setBlob(String parameterName, InputStream inputStream) throws java.sql.SQLException { delegate.setBlob(parameterName, inputStream); }
    @Override
    public void setClob(String parameterName, Clob x) throws java.sql.SQLException { delegate.setClob(parameterName, x); }
    @Override
    public void setClob(String parameterName, Reader reader, long length) throws java.sql.SQLException { delegate.setClob(parameterName, reader, length); }
    @Override
    public void setClob(String parameterName, Reader reader) throws java.sql.SQLException { delegate.setClob(parameterName, reader); }
    @Override
    public NClob getNClob(int parameterIndex) throws java.sql.SQLException { return delegate.getNClob(parameterIndex); }
    @Override
    public NClob getNClob(String parameterName) throws java.sql.SQLException { return delegate.getNClob(parameterName); }
    @Override
    public void setNClob(String parameterName, NClob value) throws java.sql.SQLException { delegate.setNClob(parameterName, value); }
    @Override
    public void setNClob(String parameterName, Reader reader, long length) throws java.sql.SQLException { delegate.setNClob(parameterName, reader, length); }
    @Override
    public void setNClob(String parameterName, Reader reader) throws java.sql.SQLException { delegate.setNClob(parameterName, reader); }
    @Override
    public SQLXML getSQLXML(int parameterIndex) throws java.sql.SQLException { return delegate.getSQLXML(parameterIndex); }
    @Override
    public SQLXML getSQLXML(String parameterName) throws java.sql.SQLException { return delegate.getSQLXML(parameterName); }
    @Override
    public void setSQLXML(String parameterName, SQLXML xmlObject) throws java.sql.SQLException { delegate.setSQLXML(parameterName, xmlObject); }
    @Override
    public String getNString(int parameterIndex) throws java.sql.SQLException { return delegate.getNString(parameterIndex); }
    @Override
    public String getNString(String parameterName) throws java.sql.SQLException { return delegate.getNString(parameterName); }
    @Override
    public Reader getNCharacterStream(int parameterIndex) throws java.sql.SQLException { return delegate.getNCharacterStream(parameterIndex); }
    @Override
    public Reader getNCharacterStream(String parameterName) throws java.sql.SQLException { return delegate.getNCharacterStream(parameterName); }
    @Override
    public void setNCharacterStream(String parameterName, Reader value, long length) throws java.sql.SQLException { delegate.setNCharacterStream(parameterName, value, length); }
    @Override
    public void setNCharacterStream(String parameterName, Reader value) throws java.sql.SQLException { delegate.setNCharacterStream(parameterName, value); }
    @Override
    public void setNString(String parameterName, String value) throws java.sql.SQLException { delegate.setNString(parameterName, value); }
    @Override
    public Reader getCharacterStream(int parameterIndex) throws java.sql.SQLException { return delegate.getCharacterStream(parameterIndex); }
    @Override
    public Reader getCharacterStream(String parameterName) throws java.sql.SQLException { return delegate.getCharacterStream(parameterName); }
    @Override
    public void registerOutParameter(int parameterIndex, SQLType sqlType) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType); }
    @Override
    public void registerOutParameter(int parameterIndex, SQLType sqlType, int scale) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType, scale); }
    @Override
    public void registerOutParameter(int parameterIndex, SQLType sqlType, String typeName) throws java.sql.SQLException { delegate.registerOutParameter(parameterIndex, sqlType, typeName); }
    @Override
    public void registerOutParameter(String parameterName, SQLType sqlType) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType); }
    @Override
    public void registerOutParameter(String parameterName, SQLType sqlType, int scale) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType, scale); }
    @Override
    public void registerOutParameter(String parameterName, SQLType sqlType, String typeName) throws java.sql.SQLException { delegate.registerOutParameter(parameterName, sqlType, typeName); }
    @Override
    public void setObject(String parameterName, Object x, SQLType targetSqlType, int scaleOrLength) throws java.sql.SQLException { delegate.setObject(parameterName, x, targetSqlType, scaleOrLength); }
    @Override
    public void setObject(String parameterName, Object x, SQLType targetSqlType) throws java.sql.SQLException { delegate.setObject(parameterName, x, targetSqlType); }
    @Override
    public long executeLargeUpdate() throws java.sql.SQLException {
        long start = System.nanoTime();
        try {
            long rows = delegate.executeLargeUpdate();
            monitor.recordUpdate(sql, System.nanoTime() - start, (int) Math.min(rows, Integer.MAX_VALUE));
            return rows;
        } catch (java.sql.SQLException e) {
            monitor.recordError(sql, System.nanoTime() - start, e);
            throw e;
        }
    }

    @Override
    public String toString() {
        return "MonitoredCallableStatement[" + delegate + "]";
    }

    @Override
    public int hashCode() { return delegate.hashCode(); }
    @Override
    public boolean equals(Object obj) { return delegate.equals(obj); }
}